// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3TehKdrPqxWRnlDWqrUbs6hLAaXiv9_k',
    appId: '1:553511067294:web:d93ab432d36d45b3d1258f',
    messagingSenderId: '553511067294',
    projectId: 'shop-easy-cc602',
    authDomain: 'shop-easy-cc602.firebaseapp.com',
    storageBucket: 'shop-easy-cc602.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB74_2NCdMz_Z4qH_GfO0LVY7p2FQbIVK4',
    appId: '1:553511067294:android:8b3377d759257292d1258f',
    messagingSenderId: '553511067294',
    projectId: 'shop-easy-cc602',
    storageBucket: 'shop-easy-cc602.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBklIWvyqqaJ6nftFD2j0DJ4VeU3DfZipc',
    appId: '1:553511067294:ios:28bc403bf4ce7a71d1258f',
    messagingSenderId: '553511067294',
    projectId: 'shop-easy-cc602',
    storageBucket: 'shop-easy-cc602.appspot.com',
    iosClientId: '553511067294-h80bsam426ra4un8uefesmlpin6vv4jt.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopEasy',
  );
}
